name: Android CI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Check Commit Message [skip CI]
        env:
          COMMIT_FILTER: "[skip ci]"
        if: contains(github.event.head_commit.message, '[skip ci]')
        run: |
          echo "no 'skip ci' in commit message"
          exit 2

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build Debug APK with Gradle
        run: |
          [ $(du -s ~/.gradle/wrapper | awk '{ print $1 }') -gt 250000 ] && rm -rf ~/.gradle/wrapper/* || true
          chmod +x gradlew
          ./gradlew assembleDebug
          echo "DEBUG_APK_PATH=$(find app/build/outputs/apk/debug -name '*.apk')" >> $GITHUB_ENV

      - name: Get version from tag
        if: github.ref_type == 'tag'
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Upload debug APK to Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          files: ${{ env.DEBUG_APK_PATH }}
          name: Release ${{ env.RELEASE_VERSION }}
          body: "Debug build for version ${{ env.RELEASE_VERSION }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}